# Generated by Django 2.0.5 on 2018-06-04 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('master', '0003_auto_20180604_1901'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendTime', models.DateTimeField()),
                ('worker', models.CharField(db_index=True, max_length=20, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('makeFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Mechine')),
                ('modiUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptId', models.CharField(db_index=True, max_length=20, unique=True)),
                ('note', models.TextField(null=True)),
                ('receiptTime', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modiUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchaseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Purchase')),
                ('receipter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Staff')),
                ('tags', models.ManyToManyField(to='master.Tag')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Company')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.FloatField()),
                ('note', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modiUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='store.Outbound')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='store.Receipt')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.partUnit')),
            ],
        ),
    ]
