# Generated by Django 2.0.5 on 2018-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20180518_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productBrand',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
