# Generated by Django 2.0.5 on 2018-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20, null=True)),
                ('specification', models.TextField()),
                ('productBrand', models.CharField(max_length=20, null=True)),
                ('bom', models.ManyToManyField(related_name='_product_bom_+', to='master.Product')),
            ],
        ),
    ]
