# Generated by Django 2.0.5 on 2018-05-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
