# Generated by Django 2.0.5 on 2018-05-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20180518_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productBrand',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
