# Generated by Django 2.0.5 on 2018-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20180514_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bom',
            field=models.ManyToManyField(to='master.Product'),
        ),
    ]
