# Generated by Django 2.0.5 on 2018-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20180514_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='partUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=20, unique=True)),
                ('conversion', models.FloatField(db_index=True)),
            ],
        ),
    ]
