# Generated by Django 2.0.5 on 2018-05-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_partunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.FloatField()),
                ('parentProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='partunit',
            name='conversion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='partunit',
            name='dimension',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='unitId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.partUnit'),
        ),
    ]
