# Generated by Django 2.0.5 on 2018-05-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20180517_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Product'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='parentProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getBom', to='master.Product'),
        ),
    ]
