# Generated by Django 2.0.5 on 2018-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20180517_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bom',
        ),
        migrations.AddField(
            model_name='bomitem',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(null=True),
        ),
    ]
